<a href="https://colab.research.google.com/github/SudiptoChowdhury25/Simulation-and-Modeling-Lab/blob/main/Lab_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use numpy to create a 3×3 matrix of random integers between 1 and 50.  
   Run the code twice

1. **With a fixed seed (`np.random.seed(10)`) to ensure reproducibility. **
2. **Without setting a seed, allowing random values to change each time. **
3. ** Observe and explain the differences in outputs.  (in a different cell
as text)**

In [8]:
import numpy as np

# With fixed seed
np.random.seed(10)
fixed_seed_matrix = np.random.randint(1, 51, (3, 3))
print("Matrix with fixed seed:\n",fixed_seed_matrix)

Matrix with fixed seed:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [13]:
# Without fixed seed
random_matrix = np.random.randint(1, 51, (3, 3))
print("\nMatrix without fixed seed:\n",random_matrix)


Matrix without fixed seed:
 [[42  7  8]
 [40 15 43]
 [36  9 27]]


**Explanation of Differences:**

**With Fixed Seed (np.random.seed(10))**

The matrix generated remains the same every time the code is executed.
This is useful for reproducibility, debugging, and testing.

**Without Fixed Seed**

The matrix changes with each execution because no seed is set.
This mimics real randomness and is useful when different outputs are required.